from django.contrib.gis.db import models
from django.utils.translation import ugettext_lazy as _

# Currency alphabetic codes. ISO 4217
CURRENCY_CHOICES = (
    ('AFN', 'AFGHANISTAN	Afghani'),
    ('EUR', 'ÅLAND ISLANDS	Euro'),
    ('ALL', 'ALBANIA	Lek'),
    ('DZD', 'ALGERIA	Algerian Dinar'),
    ('USD', 'AMERICAN SAMOA	US Dollar'),
    ('EUR', 'ANDORRA	Euro'),
    ('AOA', 'ANGOLA	Kwanza'),
    ('XCD', 'ANGUILLA	East Caribbean Dollar'),
    ('XCD', 'ANTIGUA AND BARBUDA	East Caribbean Dollar'),
    ('ARS', 'ARGENTINA	Argentine Peso'),
    ('AMD', 'ARMENIA	Armenian Dram'),
    ('AWG', 'ARUBA	Aruban Florin'),
    ('AUD', 'AUSTRALIA	Australian Dollar'),
    ('EUR', 'AUSTRIA	Euro'),
    ('AZN', 'AZERBAIJAN	Azerbaijan Manat'),
    ('BSD', 'BAHAMAS (THE)	Bahamian Dollar'),
    ('BHD', 'BAHRAIN	Bahraini Dinar'),
    ('BDT', 'BANGLADESH	Taka'),
    ('BBD', 'BARBADOS	Barbados Dollar'),
    ('BYN', 'BELARUS	Belarusian Ruble'),
    ('EUR', 'BELGIUM	Euro'),
    ('BZD', 'BELIZE	Belize Dollar'),
    ('XOF', 'BENIN	CFA Franc BCEAO'),
    ('BMD', 'BERMUDA	Bermudian Dollar'),
    ('INR', 'BHUTAN	Indian Rupee'),
    ('BTN', 'BHUTAN	Ngultrum'),
    ('BOB', 'BOLIVIA (PLURINATIONAL STATE OF)	Boliviano'),
    ('BOV', 'BOLIVIA (PLURINATIONAL STATE OF)	Mvdol'),
    ('USD', 'BONAIRE, SINT EUSTATIUS AND SABA	US Dollar'),
    ('BAM', 'BOSNIA AND HERZEGOVINA	Convertible Mark'),
    ('BWP', 'BOTSWANA	Pula'),
    ('NOK', 'BOUVET ISLAND	Norwegian Krone'),
    ('BRL', 'BRAZIL	Brazilian Real'),
    ('USD', 'BRITISH INDIAN OCEAN TERRITORY (THE)	US Dollar'),
    ('BND', 'BRUNEI DARUSSALAM	Brunei Dollar'),
    ('BGN', 'BULGARIA	Bulgarian Lev'),
    ('XOF', 'BURKINA FASO	CFA Franc BCEAO'),
    ('BIF', 'BURUNDI	Burundi Franc'),
    ('CVE', 'CABO VERDE	Cabo Verde Escudo'),
    ('KHR', 'CAMBODIA	Riel'),
    ('XAF', 'CAMEROON	CFA Franc BEAC'),
    ('CAD', 'CANADA	Canadian Dollar'),
    ('KYD', 'CAYMAN ISLANDS (THE)	Cayman Islands Dollar'),
    ('XAF', 'CENTRAL AFRICAN REPUBLIC (THE)	CFA Franc BEAC'),
    ('XAF', 'CHAD	CFA Franc BEAC'),
    ('CLP', 'CHILE	Chilean Peso'),
    ('CLF', 'CHILE	Unidad de Fomento'),
    ('CNY', 'CHINA	Yuan Renminbi'),
    ('AUD', 'CHRISTMAS ISLAND	Australian Dollar'),
    ('AUD', 'COCOS (KEELING) ISLANDS (THE)	Australian Dollar'),
    ('COP', 'COLOMBIA	Colombian Peso'),
    ('COU', 'COLOMBIA	Unidad de Valor Real'),
    ('KMF', 'COMOROS (THE)	Comorian Franc '),
    ('CDF', 'CONGO (THE DEMOCRATIC REPUBLIC OF THE)	Congolese Franc'),
    ('XAF', 'CONGO (THE)	CFA Franc BEAC'),
    ('NZD', 'COOK ISLANDS (THE)	New Zealand Dollar'),
    ('CRC', 'COSTA RICA	Costa Rican Colon'),
    ('XOF', 'CÔTE D\'IVOIRE	CFA Franc BCEAO'),
    ('HRK', 'CROATIA	Kuna'),
    ('CUP', 'CUBA	Cuban Peso'),
    ('CUC', 'CUBA	Peso Convertible'),
    ('ANG', 'CURAÇAO	Netherlands Antillean Guilder'),
    ('EUR', 'CYPRUS	Euro'),
    ('CZK', 'CZECHIA	Czech Koruna'),
    ('DKK', 'DENMARK	Danish Krone'),
    ('DJF', 'DJIBOUTI	Djibouti Franc'),
    ('XCD', 'DOMINICA	East Caribbean Dollar'),
    ('DOP', 'DOMINICAN REPUBLIC (THE)	Dominican Peso'),
    ('USD', 'ECUADOR	US Dollar'),
    ('EGP', 'EGYPT	Egyptian Pound'),
    ('SVC', 'EL SALVADOR	El Salvador Colon'),
    ('USD', 'EL SALVADOR	US Dollar'),
    ('XAF', 'EQUATORIAL GUINEA	CFA Franc BEAC'),
    ('ERN', 'ERITREA	Nakfa'),
    ('EUR', 'ESTONIA	Euro'),
    ('ETB', 'ETHIOPIA	Ethiopian Birr'),
    ('EUR', 'EUROPEAN UNION	Euro'),
    ('FKP', 'FALKLAND ISLANDS (THE) [MALVINAS]	Falkland Islands Pound'),
    ('DKK', 'FAROE ISLANDS (THE)	Danish Krone'),
    ('FJD', 'FIJI	Fiji Dollar'),
    ('EUR', 'FINLAND	Euro'),
    ('EUR', 'FRANCE	Euro'),
    ('EUR', 'FRENCH GUIANA	Euro'),
    ('XPF', 'FRENCH POLYNESIA	CFP Franc'),
    ('EUR', 'FRENCH SOUTHERN TERRITORIES (THE)	Euro'),
    ('XAF', 'GABON	CFA Franc BEAC'),
    ('GMD', 'GAMBIA (THE)	Dalasi'),
    ('GEL', 'GEORGIA	Lari'),
    ('EUR', 'GERMANY	Euro'),
    ('GHS', 'GHANA	Ghana Cedi'),
    ('GIP', 'GIBRALTAR	Gibraltar Pound'),
    ('EUR', 'GREECE	Euro'),
    ('DKK', 'GREENLAND	Danish Krone'),
    ('XCD', 'GRENADA	East Caribbean Dollar'),
    ('EUR', 'GUADELOUPE	Euro'),
    ('USD', 'GUAM	US Dollar'),
    ('GTQ', 'GUATEMALA	Quetzal'),
    ('GBP', 'GUERNSEY	Pound Sterling'),
    ('GNF', 'GUINEA	Guinean Franc'),
    ('XOF', 'GUINEA-BISSAU	CFA Franc BCEAO'),
    ('GYD', 'GUYANA	Guyana Dollar'),
    ('HTG', 'HAITI	Gourde'),
    ('USD', 'HAITI	US Dollar'),
    ('AUD', 'HEARD ISLAND AND McDONALD ISLANDS	Australian Dollar'),
    ('EUR', 'HOLY SEE (THE)	Euro'),
    ('HNL', 'HONDURAS	Lempira'),
    ('HKD', 'HONG KONG	Hong Kong Dollar'),
    ('HUF', 'HUNGARY	Forint'),
    ('ISK', 'ICELAND	Iceland Krona'),
    ('INR', 'INDIA	Indian Rupee'),
    ('IDR', 'INDONESIA	Rupiah'),
    ('XDR', 'INTERNATIONAL MONETARY FUND (IMF) 	SDR (Special Drawing Right)'),
    ('IRR', 'IRAN (ISLAMIC REPUBLIC OF)	Iranian Rial'),
    ('IQD', 'IRAQ	Iraqi Dinar'),
    ('EUR', 'IRELAND	Euro'),
    ('GBP', 'ISLE OF MAN	Pound Sterling'),
    ('ILS', 'ISRAEL	New Israeli Sheqel'),
    ('EUR', 'ITALY	Euro'),
    ('JMD', 'JAMAICA	Jamaican Dollar'),
    ('JPY', 'JAPAN	Yen'),
    ('GBP', 'JERSEY	Pound Sterling'),
    ('JOD', 'JORDAN	Jordanian Dinar'),
    ('KZT', 'KAZAKHSTAN	Tenge'),
    ('KES', 'KENYA	Kenyan Shilling'),
    ('AUD', 'KIRIBATI	Australian Dollar'),
    ('KPW', 'KOREA (THE DEMOCRATIC PEOPLE’S REPUBLIC OF)	North Korean Won'),
    ('KRW', 'KOREA (THE REPUBLIC OF)	Won'),
    ('KWD', 'KUWAIT	Kuwaiti Dinar'),
    ('KGS', 'KYRGYZSTAN	Som'),
    ('LAK', 'LAO PEOPLE’S DEMOCRATIC REPUBLIC (THE)	Lao Kip'),
    ('EUR', 'LATVIA	Euro'),
    ('LBP', 'LEBANON	Lebanese Pound'),
    ('LSL', 'LESOTHO	Loti'),
    ('ZAR', 'LESOTHO	Rand'),
    ('LRD', 'LIBERIA	Liberian Dollar'),
    ('LYD', 'LIBYA	Libyan Dinar'),
    ('CHF', 'LIECHTENSTEIN	Swiss Franc'),
    ('EUR', 'LITHUANIA	Euro'),
    ('EUR', 'LUXEMBOURG	Euro'),
    ('MOP', 'MACAO	Pataca'),
    ('MKD', 'MACEDONIA (THE FORMER YUGOSLAV REPUBLIC OF)	Denar'),
    ('MGA', 'MADAGASCAR	Malagasy Ariary'),
    ('MWK', 'MALAWI	Malawi Kwacha'),
    ('MYR', 'MALAYSIA	Malaysian Ringgit'),
    ('MVR', 'MALDIVES	Rufiyaa'),
    ('XOF', 'MALI	CFA Franc BCEAO'),
    ('EUR', 'MALTA	Euro'),
    ('USD', 'MARSHALL ISLANDS (THE)	US Dollar'),
    ('EUR', 'MARTINIQUE	Euro'),
    ('MRU', 'MAURITANIA	Ouguiya'),
    ('MUR', 'MAURITIUS	Mauritius Rupee'),
    ('EUR', 'MAYOTTE	Euro'),
    ('XUA', 'MEMBER COUNTRIES OF THE AFRICAN DEVELOPMENT BANK GROUP	ADB Unit of Account'),
    ('MXN', 'MEXICO	Mexican Peso'),
    ('MXV', 'MEXICO	Mexican Unidad de Inversion (UDI)'),
    ('USD', 'MICRONESIA (FEDERATED STATES OF)	US Dollar'),
    ('MDL', 'MOLDOVA (THE REPUBLIC OF)	Moldovan Leu'),
    ('EUR', 'MONACO	Euro'),
    ('MNT', 'MONGOLIA	Tugrik'),
    ('EUR', 'MONTENEGRO	Euro'),
    ('XCD', 'MONTSERRAT	East Caribbean Dollar'),
    ('MAD', 'MOROCCO	Moroccan Dirham'),
    ('MZN', 'MOZAMBIQUE	Mozambique Metical'),
    ('MMK', 'MYANMAR	Kyat'),
    ('NAD', 'NAMIBIA	Namibia Dollar'),
    ('ZAR', 'NAMIBIA	Rand'),
    ('AUD', 'NAURU	Australian Dollar'),
    ('NPR', 'NEPAL	Nepalese Rupee'),
    ('EUR', 'NETHERLANDS (THE)	Euro'),
    ('XPF', 'NEW CALEDONIA	CFP Franc'),
    ('NZD', 'NEW ZEALAND	New Zealand Dollar'),
    ('NIO', 'NICARAGUA	Cordoba Oro'),
    ('XOF', 'NIGER (THE)	CFA Franc BCEAO'),
    ('NGN', 'NIGERIA	Naira'),
    ('NZD', 'NIUE	New Zealand Dollar'),
    ('AUD', 'NORFOLK ISLAND	Australian Dollar'),
    ('USD', 'NORTHERN MARIANA ISLANDS (THE)	US Dollar'),
    ('NOK', 'NORWAY	Norwegian Krone'),
    ('OMR', 'OMAN	Rial Omani'),
    ('PKR', 'PAKISTAN	Pakistan Rupee'),
    ('USD', 'PALAU	US Dollar'),
    ('PAB', 'PANAMA	Balboa'),
    ('USD', 'PANAMA	US Dollar'),
    ('PGK', 'PAPUA NEW GUINEA	Kina'),
    ('PYG', 'PARAGUAY	Guarani'),
    ('PEN', 'PERU	Sol'),
    ('PHP', 'PHILIPPINES (THE)	Philippine Peso'),
    ('NZD', 'PITCAIRN	New Zealand Dollar'),
    ('PLN', 'POLAND	Zloty'),
    ('EUR', 'PORTUGAL	Euro'),
    ('USD', 'PUERTO RICO	US Dollar'),
    ('QAR', 'QATAR	Qatari Rial'),
    ('EUR', 'RÉUNION	Euro'),
    ('RON', 'ROMANIA	Romanian Leu'),
    ('RUB', 'RUSSIAN FEDERATION (THE)	Russian Ruble'),
    ('RWF', 'RWANDA	Rwanda Franc'),
    ('EUR', 'SAINT BARTHÉLEMY	Euro'),
    ('SHP', 'SAINT HELENA, ASCENSION AND TRISTAN DA CUNHA	Saint Helena Pound'),
    ('XCD', 'SAINT KITTS AND NEVIS	East Caribbean Dollar'),
    ('XCD', 'SAINT LUCIA	East Caribbean Dollar'),
    ('EUR', 'SAINT MARTIN (FRENCH PART)	Euro'),
    ('EUR', 'SAINT PIERRE AND MIQUELON	Euro'),
    ('XCD', 'SAINT VINCENT AND THE GRENADINES	East Caribbean Dollar'),
    ('WST', 'SAMOA	Tala'),
    ('EUR', 'SAN MARINO	Euro'),
    ('STN', 'SAO TOME AND PRINCIPE	Dobra'),
    ('SAR', 'SAUDI ARABIA	Saudi Riyal'),
    ('XOF', 'SENEGAL	CFA Franc BCEAO'),
    ('RSD', 'SERBIA	Serbian Dinar'),
    ('SCR', 'SEYCHELLES	Seychelles Rupee'),
    ('SLL', 'SIERRA LEONE	Leone'),
    ('SGD', 'SINGAPORE	Singapore Dollar'),
    ('ANG', 'SINT MAARTEN (DUTCH PART)	Netherlands Antillean Guilder'),
    ('XSU', 'SISTEMA UNITARIO DE COMPENSACION REGIONAL DE PAGOS "SUCRE"	Sucre'),
    ('EUR', 'SLOVAKIA	Euro'),
    ('EUR', 'SLOVENIA	Euro'),
    ('SBD', 'SOLOMON ISLANDS	Solomon Islands Dollar'),
    ('SOS', 'SOMALIA	Somali Shilling'),
    ('ZAR', 'SOUTH AFRICA	Rand'),
    ('SSP', 'SOUTH SUDAN	South Sudanese Pound'),
    ('EUR', 'SPAIN	Euro'),
    ('LKR', 'SRI LANKA	Sri Lanka Rupee'),
    ('SDG', 'SUDAN (THE)	Sudanese Pound'),
    ('SRD', 'SURINAME	Surinam Dollar'),
    ('NOK', 'SVALBARD AND JAN MAYEN	Norwegian Krone'),
    ('SZL', 'ESWATINI	Lilangeni'),
    ('SEK', 'SWEDEN	Swedish Krona'),
    ('CHF', 'SWITZERLAND	Swiss Franc'),
    ('CHE', 'SWITZERLAND	WIR Euro'),
    ('CHW', 'SWITZERLAND	WIR Franc'),
    ('SYP', 'SYRIAN ARAB REPUBLIC	Syrian Pound'),
    ('TWD', 'TAIWAN (PROVINCE OF CHINA)	New Taiwan Dollar'),
    ('TJS', 'TAJIKISTAN	Somoni'),
    ('TZS', 'TANZANIA, UNITED REPUBLIC OF	Tanzanian Shilling'),
    ('THB', 'THAILAND	Baht'),
    ('USD', 'TIMOR-LESTE	US Dollar'),
    ('XOF', 'TOGO	CFA Franc BCEAO'),
    ('NZD', 'TOKELAU	New Zealand Dollar'),
    ('TOP', 'TONGA	Pa’anga'),
    ('TTD', 'TRINIDAD AND TOBAGO	Trinidad and Tobago Dollar'),
    ('TND', 'TUNISIA	Tunisian Dinar'),
    ('TRY', 'TURKEY	Turkish Lira'),
    ('TMT', 'TURKMENISTAN	Turkmenistan New Manat'),
    ('USD', 'TURKS AND CAICOS ISLANDS (THE)	US Dollar'),
    ('AUD', 'TUVALU	Australian Dollar'),
    ('UGX', 'UGANDA	Uganda Shilling'),
    ('UAH', 'UKRAINE	Hryvnia'),
    ('AED', 'UNITED ARAB EMIRATES (THE)	UAE Dirham'),
    ('GBP', 'UNITED KINGDOM OF GREAT BRITAIN AND NORTHERN IRELAND (THE)	Pound Sterling'),
    ('USD', 'UNITED STATES MINOR OUTLYING ISLANDS (THE)	US Dollar'),
    ('USD', 'UNITED STATES OF AMERICA (THE)	US Dollar'),
    ('USN', 'UNITED STATES OF AMERICA (THE)	US Dollar (Next day)'),
    ('UYU', 'URUGUAY	Peso Uruguayo'),
    ('UYI', 'URUGUAY	Uruguay Peso en Unidades Indexadas (UI)'),
    ('UYW', 'URUGUAY	Unidad Previsional'),
    ('UZS', 'UZBEKISTAN	Uzbekistan Sum'),
    ('VUV', 'VANUATU	Vatu'),
    ('VES', 'VENEZUELA (BOLIVARIAN REPUBLIC OF)	Bolívar Soberano'),
    ('VND', 'VIET NAM	Dong'),
    ('USD', 'VIRGIN ISLANDS (BRITISH)	US Dollar'),
    ('USD', 'VIRGIN ISLANDS (U.S.)	US Dollar'),
    ('XPF', 'WALLIS AND FUTUNA	CFP Franc'),
    ('MAD', 'WESTERN SAHARA	Moroccan Dirham'),
    ('YER', 'YEMEN	Yemeni Rial'),
    ('ZMW', 'ZAMBIA	Zambian Kwacha'),
    ('ZWL', 'ZIMBABWE	Zimbabwe Dollar'),
)

# Language codes. RFC 3066. It's not full list of codes. This codes just for example.
LANGUAGE_CHOICES = (
    ('en-US', 'United States English'),
    ('en-GB', 'United Kingdom English'),
    ('ru-RU', 'Russian'),
)


class ServiceArea(models.Model):
    """
    Service area of provider
    """
    # Name of service area
    name = models.CharField(max_length=50)
    # Price
    price = models.DecimalField(max_digits=6, decimal_places=2)
    # Currency alphabetic code. ISO 4217. See: https://www.currency-iso.org/en/home/tables/table-a1.html
    currency = models.CharField(choices=CURRENCY_CHOICES, max_length=50)
    # GeoDjango-specific: a geometry field (MultiPolygonField)
    poly = models.MultiPolygonField()

    class Meta:
        verbose_name = _('Service Area')
        verbose_name_plural = _('Service Areas')
        ordering = ['name']

    def __str__(self):
        return '[{}] {}'.format(self.pk, self.name)


class Provider(models.Model):
    """
    Provider (transportation supplier)
    """
    # Provider name
    name = models.CharField(max_length=255)
    # Email
    email = models.EmailField()
    # Phone number
    phone = models.CharField(max_length=255)
    # Language code. RFC 3066. See: http://www.i18nguy.com/unicode/language-identifiers.html
    language = models.CharField(choices=LANGUAGE_CHOICES, max_length=50)
    # Currency alphabetic code. ISO 4217. See: https://www.currency-iso.org/en/home/tables/table-a1.html
    currency = models.CharField(choices=CURRENCY_CHOICES, max_length=50)
    # Provider can have multiple service areas
    service_areas = models.ManyToManyField(ServiceArea)

    class Meta:
        verbose_name = _('Provider')
        verbose_name_plural = _('Providers')
        ordering = ['name']

    def __str__(self):
        return '[{}] {}'.format(self.pk, self.name)
